jobs:
- template: _build/azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13

- template: _build/azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
