[package]
name = "chip8"
version = "0.1.0"
authors = ["Kevin Caffrey"]
edition = "2018"
license = "MIT"
publish = false
readme = "README.md"

[dependencies]
rand = "0.5"
clap = "2.32.0"
ggez = "0.4.4"

[dependencies.rodio]
version = "0.8.1"
default-features = false